services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: trc
      POSTGRES_PASSWORD: trc
      POSTGRES_DB: the_right_choice
    ports:
      - "5432:5432"
    volumes:
      - trc_db_data:/var/lib/postgresql/data

volumes:
  trc_db_data:
