export const productSeedData = [
  { name: "Choice Jumbo", category: "Breads & Snacks", cost: null, price: 2000, initialStock: 0 },
  { name: "Choice Prime", category: "Breads & Snacks", cost: null, price: null, initialStock: 0 },
  { name: "Choice Family Size", category: "Breads & Snacks", cost: null, price: 1500, initialStock: 0 },
  { name: "So Soft Jumbo", category: "Breads & Snacks", cost: 1800, price: 2000, initialStock: 0 },
  { name: "So Soft Family", category: "Breads & Snacks", cost: 1400, price: 1500, initialStock: 19 },
  { name: "Coconut Bread", category: "Breads & Snacks", cost: null, price: 2000, initialStock: 0 },
  { name: "Milk Bread", category: "Breads & Snacks", cost: null, price: 2000, initialStock: 0 },
  { name: "Cake Bread", category: "Breads & Snacks", cost: null, price: 2000, initialStock: 0 },
  { name: "Sardine Bread", category: "Breads & Snacks", cost: null, price: 2000, initialStock: 0 },
  { name: "Meat Pie", category: "Breads & Snacks", cost: null, price: 800, initialStock: 0 },
  { name: "Chicken Pie", category: "Breads & Snacks", cost: null, price: 800, initialStock: 0 },
  { name: "Sausage Roll", category: "Breads & Snacks", cost: null, price: 600, initialStock: 0 },
  { name: "Super Roll", category: "Breads & Snacks", cost: null, price: 900, initialStock: 0 },
  { name: "Egg Roll", category: "Breads & Snacks", cost: null, price: 600, initialStock: 0 },
  { name: "Chopmore", category: "Breads & Snacks", cost: null, price: 900, initialStock: 1 },
  { name: "Donuts", category: "Breads & Snacks", cost: null, price: 500, initialStock: 0 },
  { name: "Jam donuts", category: "Breads & Snacks", cost: null, price: 600, initialStock: 0 },
  { name: "Cup Cake", category: "Breads & Snacks", cost: null, price: 500, initialStock: 0 },
  { name: "Foil Cake", category: "Breads & Snacks", cost: null, price: 2000, initialStock: 0 },
  { name: "Special Cake", category: "Breads & Snacks", cost: null, price: null, initialStock: 0 },
  { name: "Order Cake", category: "Breads & Snacks", cost: null, price: null, initialStock: 0 },
  { name: "Gala", category: "Breads & Snacks", cost: null, price: 200, initialStock: 1 },
  { name: "Plantain Chips", category: "Breads & Snacks", cost: null, price: 5000, initialStock: 1 },
  { name: "Chin Chin", category: "Breads & Snacks", cost: null, price: 6000, initialStock: 0 },
  { name: "Local Snacks", category: "Breads & Snacks", cost: 1000, price: 1200, initialStock: 10 },
  { name: "Bottle Chocolate", category: "Breads & Snacks", cost: null, price: null, initialStock: 0 },
  { name: "Bounty", category: "Breads & Snacks", cost: null, price: 1400, initialStock: 11 },
  { name: "Snickers", category: "Breads & Snacks", cost: null, price: 1300, initialStock: 0 },
  { name: "Pringles", category: "Breads & Snacks", cost: null, price: 3500, initialStock: 2 },
  { name: "Fan Ice Cream 3Ltrs", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Fan Ice Cream 2Ltrs", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Fan Ice Cream 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 3875, price: 4700, initialStock: 1 },
  { name: "Fan Ice Cream 450ml", category: "Ice Cream, Yoghurt & Parfait", cost: 2432, price: 3250, initialStock: 41 },
  { name: "Fan Ice Cream 250ml", category: "Ice Cream, Yoghurt & Parfait", cost: 1090, price: 1650, initialStock: 12 },
  { name: "Fan Ice Cream 120ml", category: "Ice Cream, Yoghurt & Parfait", cost: 527, price: 850, initialStock: 44 },
  { name: "Fan Ice Cream Vanilla Sachet", category: "Ice Cream, Yoghurt & Parfait", cost: 362, price: 600, initialStock: 31 },
  { name: "Fan Ice Cream Strawberry Sachet", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 650, initialStock: 0 },
  { name: "Fan Ice Cream Go Slo BIG", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Fan Ice Cream Go Slo Small", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Fan Ice Cream Chips", category: "Ice Cream, Yoghurt & Parfait", cost: 4939, price: 5500, initialStock: 1 },
  { name: "Supreme 3Ltrs", category: "Ice Cream, Yoghurt & Parfait", cost: 9425, price: 11000, initialStock: 0 },
  { name: "Supreme 2Ltrs", category: "Ice Cream, Yoghurt & Parfait", cost: 5765.25, price: 7200, initialStock: 0 },
  { name: "Supreme 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 3384.5, price: 4700, initialStock: 3 },
  { name: "Supreme 450ml", category: "Ice Cream, Yoghurt & Parfait", cost: 1994.75, price: 3250, initialStock: 3 },
  { name: "Supreme 250ml", category: "Ice Cream, Yoghurt & Parfait", cost: 829.79, price: 1650, initialStock: 0 },
  { name: "Supreme 120ml", category: "Ice Cream, Yoghurt & Parfait", cost: 419.3, price: 850, initialStock: 54 },
  { name: "Supreme Sachet", category: "Ice Cream, Yoghurt & Parfait", cost: 425.5, price: 600, initialStock: 0 },
  { name: "Frosty Bites 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 3750, price: 4800, initialStock: 4 },
  { name: "Frosty Bites 500ml", category: "Ice Cream, Yoghurt & Parfait", cost: 2500, price: 3200, initialStock: 1 },
  { name: "Frosty Bites 250ml", category: "Ice Cream, Yoghurt & Parfait", cost: 1125, price: 1800, initialStock: 0 },
  { name: "Frosty Bites Cup", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 1200, initialStock: 0 },
  { name: "Frosty Bites Popsicles", category: "Ice Cream, Yoghurt & Parfait", cost: 1000, price: 1500, initialStock: 31 },
  { name: "Frosty Bites Crunch Peanut", category: "Ice Cream, Yoghurt & Parfait", cost: 1100, price: 1600, initialStock: 0 },
  { name: "Hollandia Big", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 1800, initialStock: 7 },
  { name: "Hollandia Midi", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 800, initialStock: 4 },
  { name: "Hollandia Small", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Habib 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 2700, price: null, initialStock: 0 },
  { name: "Habib 500ml", category: "Ice Cream, Yoghurt & Parfait", cost: 1400, price: 2200, initialStock: 4 },
  { name: "Habib Big Cup", category: "Ice Cream, Yoghurt & Parfait", cost: 1700, price: 2700, initialStock: 0 },
  { name: "Habib Small Cup", category: "Ice Cream, Yoghurt & Parfait", cost: 1100, price: null, initialStock: 0 },
  { name: "Habib Bottle", category: "Ice Cream, Yoghurt & Parfait", cost: 900, price: 1500, initialStock: 1 },
  { name: "Rufaidah 2Ltrs", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Rufaidah 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 3000, price: 4200, initialStock: 4 },
  { name: "Rufaidah Big Cup", category: "Ice Cream, Yoghurt & Parfait", cost: 1500, price: 2700, initialStock: 18 },
  { name: "Rufaidah Small Cup", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Rufaidah Bottle", category: "Ice Cream, Yoghurt & Parfait", cost: 1000, price: 1500, initialStock: 23 },
  { name: "Rufaidah Fruity", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 4200, initialStock: 0 },
  { name: "Nutri Choco", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: null, initialStock: 0 },
  { name: "Viju Yoghurt", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 800, initialStock: 29 },
  { name: "RC Yoghurt", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 1300, initialStock: 1 },
  { name: "Yoghurt Parfait", category: "Ice Cream, Yoghurt & Parfait", cost: 3000, price: 4200, initialStock: 13 },
  { name: "Cake Parfait", category: "Ice Cream, Yoghurt & Parfait", cost: 3000, price: 4000, initialStock: 2 },
  { name: "Farmfresh 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 4570, price: 5000, initialStock: 0 },
  { name: "Farmfresh 500ml", category: "Ice Cream, Yoghurt & Parfait", cost: 2520, price: 3000, initialStock: 0 },
  { name: "Farmfresh Greek", category: "Ice Cream, Yoghurt & Parfait", cost: 3150, price: 3500, initialStock: 0 },
  { name: "Refresh 1Ltr", category: "Ice Cream, Yoghurt & Parfait", cost: 3780, price: 5000, initialStock: 0 },
  { name: "Refresh 500ml", category: "Ice Cream, Yoghurt & Parfait", cost: 2100, price: 3000, initialStock: 1 },
  { name: "Vita Milk", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 2000, initialStock: 7 },
  { name: "Fura", category: "Ice Cream, Yoghurt & Parfait", cost: null, price: 200, initialStock: 0 },
  { name: "Drinks", category: "Drinks & Water", cost: 375, price: 500, initialStock: 61 },
  { name: "Water", category: "Drinks & Water", cost: 120.8, price: 200, initialStock: 11 },
  { name: "Cway", category: "Drinks & Water", cost: 1700, price: 1900, initialStock: 7 },
  { name: "Dudu Juice", category: "Drinks & Water", cost: null, price: 600, initialStock: 0 },
  { name: "Sosa Big/five Alive", category: "Drinks & Water", cost: null, price: 1500, initialStock: 8 },
  { name: "Sosa Small", category: "Drinks & Water", cost: null, price: 600, initialStock: 1 },
  { name: "Energy Drink", category: "Drinks & Water", cost: 383, price: 600, initialStock: 18 },
  { name: "Viju Choco", category: "Drinks & Water", cost: 958, price: 1200, initialStock: 12 },
  { name: "Viju Wheat", category: "Drinks & Water", cost: 958, price: 1200, initialStock: 0 },
  { name: "Maltina Pet", category: "Drinks & Water", cost: 708, price: 1000, initialStock: 10 },
  { name: "Lucozade Boost", category: "Drinks & Water", cost: null, price: 1000, initialStock: 11 },
  { name: "Flying Fish", category: "Drinks & Water", cost: null, price: 1200, initialStock: 17 },
  { name: "Exotic Big", category: "Drinks & Water", cost: null, price: 1500, initialStock: 9 },
  { name: "Exotic Midi", category: "Drinks & Water", cost: null, price: 1200, initialStock: 6 },
  { name: "Exotic Can", category: "Drinks & Water", cost: null, price: 800, initialStock: 9 },
  { name: "Can Drinks", category: "Drinks & Water", cost: null, price: 700, initialStock: 30 },
  { name: "Can Schweppes", category: "Drinks & Water", cost: null, price: 700, initialStock: 19 },
  { name: "Can Farouz", category: "Drinks & Water", cost: null, price: 800, initialStock: 10 },
  { name: "Can Malt - 850", category: "Drinks & Water", cost: null, price: 850, initialStock: 14 },
  { name: "Smirnoff Ice", category: "Drinks & Water", cost: null, price: 1500, initialStock: 9 },
  { name: "Monster", category: "Drinks & Water", cost: null, price: 1200, initialStock: 3 },
  { name: "Smooth/Origin", category: "Drinks & Water", cost: null, price: 1500, initialStock: 26 },
  { name: "Bullet", category: "Drinks & Water", cost: null, price: 1500, initialStock: 15 },
  { name: "Chivita Active Big", category: "Drinks & Water", cost: null, price: 2200, initialStock: 0 },
  { name: "Chivita Active Midi", category: "Drinks & Water", cost: null, price: null, initialStock: 0 },
  { name: "Chivita Orange", category: "Drinks & Water", cost: null, price: 2200, initialStock: 0 },
  { name: "Chivita Grapes", category: "Drinks & Water", cost: null, price: 2200, initialStock: 0 },
  { name: "pocari Sweat", category: "Drinks & Water", cost: 943, price: 1200, initialStock: 24 },
  { name: "Milo Refill", category: "Provisions, Biscuits & Sweets", cost: null, price: 3700, initialStock: 1 },
  { name: "Dano Refill", category: "Provisions, Biscuits & Sweets", cost: null, price: 3500, initialStock: 0 },
  { name: "Peak Refill", category: "Provisions, Biscuits & Sweets", cost: null, price: 4200, initialStock: 0 },
  { name: "3 Crown Refill", category: "Provisions, Biscuits & Sweets", cost: null, price: 3200, initialStock: 0 },
  { name: "Evap Liquid", category: "Provisions, Biscuits & Sweets", cost: null, price: 1000, initialStock: 21 },
  { name: "Peak Liquid", category: "Provisions, Biscuits & Sweets", cost: null, price: 850, initialStock: 0 },
  { name: "3 Crown Liquid", category: "Provisions, Biscuits & Sweets", cost: null, price: 850, initialStock: 0 },
  { name: "Peak Sachet", category: "Provisions, Biscuits & Sweets", cost: null, price: 250, initialStock: 0 },
  { name: "3 Crown Sachet", category: "Provisions, Biscuits & Sweets", cost: null, price: 250, initialStock: 2 },
  { name: "Milo Sachet", category: "Provisions, Biscuits & Sweets", cost: null, price: 250, initialStock: 0 },
  { name: "3 in 1 Milo Sachet", category: "Provisions, Biscuits & Sweets", cost: null, price: 300, initialStock: 0 },
  { name: "Cashew Nut", category: "Provisions, Biscuits & Sweets", cost: null, price: 6500, initialStock: 2 },
  { name: "Ground Nut", category: "Provisions, Biscuits & Sweets", cost: null, price: 3000, initialStock: 0 },
  { name: "Shortbread Big", category: "Provisions, Biscuits & Sweets", cost: null, price: 2600, initialStock: 0 },
  { name: "Shortbread Small", category: "Provisions, Biscuits & Sweets", cost: null, price: 1600, initialStock: 3 },
  { name: "Munchkins", category: "Provisions, Biscuits & Sweets", cost: null, price: 500, initialStock: 1 },
  { name: "Fab Biscuit", category: "Provisions, Biscuits & Sweets", cost: null, price: 500, initialStock: 1 },
  { name: "Mentos Chupa Belt", category: "Provisions, Biscuits & Sweets", cost: null, price: 100, initialStock: 0 },
  { name: "Mentos Chupa", category: "Provisions, Biscuits & Sweets", cost: null, price: 200, initialStock: 0 },
  { name: "Mentos Long", category: "Provisions, Biscuits & Sweets", cost: null, price: 500, initialStock: 3 },
  { name: "Mentos Short", category: "Provisions, Biscuits & Sweets", cost: null, price: 250, initialStock: 0 },
  { name: "Mentos Big Cup", category: "Provisions, Biscuits & Sweets", cost: null, price: 3500, initialStock: 7 },
  { name: "Mentos Midi Cup", category: "Provisions, Biscuits & Sweets", cost: null, price: 2500, initialStock: 6 },
  { name: "Mentos Small Cup", category: "Provisions, Biscuits & Sweets", cost: null, price: 1000, initialStock: 32 },
  { name: "Mentos Sachet - 350", category: "Provisions, Biscuits & Sweets", cost: null, price: 350, initialStock: 19 },
  { name: "Mentos Sweet - 350", category: "Provisions, Biscuits & Sweets", cost: null, price: 350, initialStock: 0 },
  { name: "Mentos Gum - 200", category: "Provisions, Biscuits & Sweets", cost: null, price: 200, initialStock: 0 },
  { name: "Centre Fresh (gum -100)", category: "Provisions, Biscuits & Sweets", cost: null, price: 100, initialStock: 0 },
  { name: "Alpenliebe Big - 350", category: "Provisions, Biscuits & Sweets", cost: null, price: 350, initialStock: 0 },
  { name: "Alpenliebe Small - 100", category: "Provisions, Biscuits & Sweets", cost: null, price: 100, initialStock: 0 },
  { name: "Flour", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Butter", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Sugar", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Yeast", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Salt", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Vegetable Oil", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Eggs", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Beef Satis", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Minced Meat", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Meat Sauce", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Chicken Sauce", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Flavours", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Improver", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Icing Sugar", category: "Bakery Raw Materials", cost: null, price: null, initialStock: 0 },
  { name: "Cake Board / Box", category: "Packaging", cost: null, price: null, initialStock: 0 },
  { name: "Nylons", category: "Packaging", cost: null, price: null, initialStock: 0 },
  { name: "Groundnut", category: "Provisions, Biscuits & Sweets", cost: null, price: null, initialStock: 2 },
  { name: "Viju Wheat/Baked Yoghurt", category: "Drinks & Water", cost: null, price: null, initialStock: 4 },
];
